test: &default

  # Credentials for REST APIs
  client_id: AbEZ_okQKsYkBtSFwzUSwnhQ6NGasqlZAIp_ccRfj-hAUBaakL3AtLWy4PUnt0DiF8CCznJAHEVXVzLw
  client_secret: EOqUR9R6GEjIXgHh_gB8ISEmxmL6LMHSEtfo5TUTIw0OluBqxFMLNGpCYZ3075IHp4afo5d5m4r_kMS6

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: jb-us-seller_api1.paypal.com
  password: WX4WTU3S8MY44S7F
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: seller@geobike.co

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
