test: &default

  # Credentials for REST APIs
  client_id: AaRcibYXYmTKOf4Fsi1Z_UQaYOdCrStr44wcHaHeiUXRWPXL8GUsScdzZwZIIMb-x0VlFTFffb_S8fZw
  client_secret: EH8GBYK1ZOOpvKGhTCbcJownICAA_UzKEUL74U0gRkrCHMzDcOLVNpDWTQ8faEMcNRrjaeqK3GRX5Pqg

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: jb-us-seller_api1.paypal.com
  password: WX4WTU3S8MY44S7F
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: seller@geobike.co

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
